# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GRAFANA_VERSION: 8.2.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-10)" >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_SHA_SHORT
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //...
    # - name: Install Python 3
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: 3.8
    # - name: Install dependencies
    #   run: |
    #     set -ex
    #     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    #     sudo apt install ./google-chrome-stable_current_amd64.deb
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    #     pip install msedge-selenium-tools
    - name: Test
      run: |
        cd e2e \
        docker-compose -f docker-compose.yml up \
          --abort-on-container-exit \
          --exit-code-from e2e
        